# Generated by Django 5.1 on 2024-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_barcode_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
